name: Python CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: install tox
        run: pip install tox==3.25.0

      - name: test
        run: tox -v
